[CI]

diff --git a/.github/workflows/upload.yml b/.github/workflows/upload.yml
--- a/.github/workflows/upload.yml
+++ b/.github/workflows/upload.yml
@@ -25,6 +25,16 @@ jobs:
           -H "${{ env.API_KEY }}" \
           -F "file=@archive.zip" \
           -F "filename=archive.zip"
+          echo "response=$response" >> $GITHUB_ENV
+
+      - name: Check API response
+        run: |
+          if [ "$(echo ${{ env.response }} | jq -r '.status')" != "1" ]; then
+            echo "Error in API response."
+            exit 1
+          fi
+        env:
+          response: ${{ env.response }}
 
       - name: Get new schem
         run: curl -X GET 'https://apiv2.craftmywebsite.fr/v1/docs/schem'
