[CI]

diff --git a/.github/workflows/upload.yml b/.github/workflows/upload.yml
--- a/.github/workflows/upload.yml
+++ b/.github/workflows/upload.yml
@@ -26,15 +26,18 @@ jobs:
           -H "${{ env.API_KEY }}" \
           -F "file=@archive.zip" \
           -F "filename=archive.zip")
-          echo "::set-output name=response::$response"
+          echo "$response" > response.json
 
       - name: Install jq
         run: sudo apt-get install -y jq
 
       - name: Check API response
-        id: check_response
         run: |
-          echo "${{ steps.send_archive.outputs.response }}" | jq -e '.status == 1' > /dev/null || { echo "Error in API response."; exit 1; }
+          status=$(cat response.json | jq -r '.status')
+          if [ "$status" != "1" ]; then
+            echo "Error in API response. Status: $status"
+            exit 1
+          fi
 
       - name: Get new schem
         run: curl -X GET 'https://apiv2.craftmywebsite.fr/v1/docs/schem'
